project:
  type: website

website:
  title: "previ_blog"
  repo-url: https://github.com/jusmendonca/previ_blog
  site-url: https://jusmendonca.quarto.pub/previ_blog/
  description: "Blog sobre Direito Previdenciário"
  repo-actions: [issue]
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/igor-mendonça-93a2b3151/
      - icon: github
        text: Github
        href: https://github.com/jusmendonca
format:
  html:
    theme: 
      light: simplex
      dark: darkly
    css: styles.css

editor: visual

