---
title: "aposentadorias"
---

## Introdução

Neste capítulo, estudaremos as aposentadorias programadas, iniciando pela regra geral vigente (após a Emenda Constitucional 103/2019). Essas aposentadorias tutelam o risco social de perda das condições de subsistência do trabalhador em decorrência da fadiga relacionada à idade avançada e ao do tempo de labor já prestado. Antes da Emenda Constitucional 103/2019, o ordenamento jurídico previa as aposentadorias por idade e por tempo de contribuição como categorias autônomas. Esses benefícios foram extintos e transformados nas chamadas aposentadorias programadas, exceto para o trabalhador rural, que ainda permanece com direito à aposentadoria por idade.

## Aposentadoria programada (regra geral)

A aposentadoria programada do RGPS tem, atualmente, fundamento no art. 201, § 7º, inciso I, da Constituição Federal e no art. 19 da Emenda Constitucional nº 103/2019.

### Requisitos

Determina o art. 19 da EC 103/2019 que "até que lei disponha sobre o tempo de contribuição a que se refere o inciso I do § 7º do art. 201 da Constituição Federal, o segurado filiado ao Regime Geral de Previdência Social após a data de entrada em vigor desta Emenda Constitucional" deverá atender aos seguintes requisitos:

-   idade mínima de 65 anos, para o homem, e 62 anos, para a mulher.

-   tempo de contribuição mínimo de 20 anos, para o homem, e 15 anos, para a mulher.

## Aposentadoria programada do professor da educação infantil, fundamental e ensino médio

Os professores da educação infantil, fundamental e ensino médio possuem requisitos diferenciados para aposentadoria se comparados com os trabalhadores em geral. Os requisitos para sua aposentadoria estão dispostos no art. 201, § 8º, da Constituição Federal e no art. 19, § 1º, II, da Emenda Constitucional nº 103/2019.

### Requisitos

Estabelece o art. 19, § 1º, da EC 103/2019 que "Até que lei complementar disponha sobre a redução de idade mínima ou tempo de contribuição prevista nos §§ 1º e 8º do art. 201 da Constituição Federal", o professor da educação infantil e no ensino fundamental e médio deverá cumprir os seguintes requisitos para aposentar-se:

-   25 anos de contribuição exclusivamente em efetivo exercício das funções de magistério na educação infantil e no ensino fundamental e médio;

-   57 anos de idade, se mulher, e 60 anos de idade, se homem.

Verifica-se que existe uma redução no requisito etário, mas, em compensação, os professores de ambos os sexos da educação infantil, ensino fundamental e médio precisam cumprir um tempo de contribuição maior do que os trabalhadores em geral.

Nos termos do art. 54, §2º do Dec. 3.048/1999 (RPS), considera-se função de magistério não apenas a docência em estabelecimento de educação básica, mas também "as funções de direção de unidade escolar e de coordenação e assessoramento pedagógicos."

Finalmente, o § 4º do mesmo dispositivo regulamentar veda a conversão de tempo de serviço de magistério, exercido em qualquer época, em tempo de serviço comum.

## Renda mensal inicial (RMI)

A RMI das aposentadorias programadas (tanto a do trabalhador em geral quanto a do professor) será de 60% do salário de benefício, mais 2% do salário de benefício a cada ano de contribuição que exceder 20 (para o homem) ou 15 (para a mulher), nos termos do art. 26, § 2º, IV, e § 5º da EC 103/2019.

Exemplificando, pelas regras atualmente vigentes, uma trabalhadora do sexo feminino (que não seja professora) que se aposente com 62 anos de idade e 17 anos de tempo de contribuição terá sua RMI calculada em 64% de seu salário de benefício (60% + 2x2%), pois ela excede, em dois, os quinze anos de contribuição.

Já uma professora da educação infantil, ensino fundamental ou médio que tenha 57 anos de idade e 27 anos de contribuição terá sua RMI calculada em 74% do salário de benefício (60% + 12x2%), pois ela excedeu em 12 os quinze anos de contribuição.

Veja-se que não se considera o excesso em relação ao tempo de contribuição mínimo para a aposentadoria do professor, mas o excesso em relação aos quinze anos de contribuição exigidos pela regra geral. Se assim não fosse, a professora, no exemplo citado, teria que trabalhar dez anos a mais que outra trabalhadora para ter a mesma renda mensal inicial, muito embora pudesse aposentar-se com cinco anos de idade a menos.

Em ambos os casos, a RMI da aposentadoria programada não pode ser inferior ao valor do salário mínimo (art. 201, § 2º, da Constituição Federal), nem ser superior ao teto do salário de contribuição do RGPS.

Finalmente, não existe limitação ao percentual de 100% do salário de benefício. Então, alguém que possua tempo de contribuição suficiente poderá obter um benefício com RMI superior a 100% do SB.

## Regras de transição da EC 103/2019

A Emenda Constitucional nº 103/2019 entrou em vigor em 13 de novembro de 2019, modificando o regramento das aposentadorias. Para os segurados filiados até aquela data, a Emenda estabeleceu algumas regras de transição, em seus artigos 15 a 21. Vejamos cada uma delas.

### Regra da pontuação, com tempo mínimo de contribuição (art. 15)

Fica assegurada a aposentadoria programada para os segurados que cumpram cumulativamente os seguintes requisitos:

-   35 anos de contribuição, se homem, ou 30 anos de contribuição, se mulher;

-   "pontuação" (tempo de contribuição somado à idade) de 96, se homem, e 86, se mulher.

Essa regra, porém, possui pontuação progressiva, aumentando-se um ponto a cada ano, até alcançar 100 (para a mulher) e 105 (para o homem), a partir de 1º de janeiro de 2020:

| *Ano de cumprimento dos requisitos* | *Pontuação (idade + tempo de contribuição)* |         |
|:------------------------|:---------------------------|:------------------|
| *Ano de cumprimento dos requisitos* | *Mulher*                                    | *Homem* |
| Até 31/12/2019                      | 86                                          | 96      |
| 2020                                | 87                                          | 97      |
| 2021                                | 88                                          | 98      |
| 2022                                | 89                                          | 99      |
| 2023                                | 90                                          | 100     |
| 2024                                | 91                                          | 101     |
| 2025                                | 92                                          | 102     |
| 2026                                | 93                                          | 103     |
| 2027                                | 94                                          | 104     |
| 2028                                | 95                                          | 105     |
| 2029                                | 96                                          | 105     |
| 2030                                | 97                                          | 105     |
| 2031                                | 98                                          | 105     |
| 2032                                | 99                                          | 105     |
| De 2033 em diante                   | 100                                         | 105     |

### Regra da idade mínima + tempo de contribuição (art. 16)

De acordo com a regra do art. 16 da EC 103/2019, fica assegurada a aposentadoria programada para os segurados que cumpram cumulativamente os seguintes requisitos:

-   35 anos de contribuição, se homem, ou 30 anos de contribuição, se mulher;

-   61 anos de idade, se homem, e 56 anos de idade, se mulher.

Essa regra possui idade mínima progressiva, a partir de janeiro de 2020, aumentando em seis meses a cada ano, até alcançar 62 (mulher) e 65 (homem):

| *Ano de cumprimento dos requisitos* | *Idade mínima* |         |
|:------------------------------------|:---------------|:--------|
| *Ano de cumprimento dos requisitos* | *Mulher*       | *Homem* |
| Até 31/12/2019                      | 56             | 61      |
| 2020                                | 56,5           | 61,5    |
| 2021                                | 57             | 62      |
| 2022                                | 57,5           | 62,5    |
| 2023                                | 58             | 63      |
| 2024                                | 58,5           | 63,5    |
| 2025                                | 59             | 64      |
| 2025                                | 59,5           | 64,5    |
| 2027                                | 60             | 65      |
| 2028                                | 60,5           | 65      |
| 2029                                | 61             | 65      |
| 2030                                | 61,5           | 65      |
| A partir de 2031                    | 62             | 65      |

### Regra do "pedágio" sem idade mínima (art. 17)

De acordo com a regra do art. 17 da EC 103/2019, fica assegurada a aposentadoria programada para os segurados que cumpram cumulativamente os seguintes requisitos:

-   tempo de contribuição mínimo, em 13/11/2019, de 33 anos, se homem, ou 28 anos, se mulher;

-   tempo de contribuição adicional de 50% sobre o que faltava, em 13/11/2019, para completar 35 anos, se homem, ou 30 anos, se mulher.

Apesar de não haver idade mínima nesta regra de transição, aplica-se o fator previdenciário para o cálculo da RMI, diminuindo seu valor, em função da expectativa de sobrevida do segurado. O § 7º do art. 29 da Lei 8.213/91 determina a fórmula de cálculo do fator previdenciário, que considerará a idade, a expectativa de sobrevida e o tempo de contribuição do segurado ao se aposentar:

$$
F = \left( 1 + \frac{N}{100} \times \left( \frac{A}{E} \right) \right){\frac{1}{2}} \times \left( 1 + \frac{E}{100} \right){\frac{1}{2}}
$$

Onde:

( F ) = Fator previdenciário; 
( N ) = Expectativa de sobrevida no momento da aposentadoria (em anos);
( A ) = Idade do trabalhador no momento da aposentadoria (em anos);
( E ) = Expectativa de sobrevida aos 65 anos (em anos).

### Regra da idade mínima + carência (art. 18)

O art. 18 da EC 103/2019 assegura a aposentadoria daqueles filiados ao RGPS até 13/11/2019, que cumpram as seguintes condições:

- 60 anos de idade, se mulher e 65 anos de idade, se homem e

- 15 anos de contribuição, para ambos os sexos.

Essa regra, porém, possui idade mínima progressiva (somente para as mulheres), a partir de janeiro de 2020, aumentando em seis meses a cada ano, até alcançar 62, na forma abaixo:

| *Ano de cumprimento dos requisitos* | *Idade mínima (anos)* |  |
| :------------- | :------------- | :------------- |
| *Ano de cumprimento dos requisitos* | *Mulher* | *Homem* |
| Até 31/12/2019 | 60 | 65 |
| 2020 | 60,5 | 65 |
| 2021 | 61 | 65 |
| 2022 | 61,5 | 65 |
| A partir de 2023 | 62 | 65 |

### Regra da idade mínima com pedágio (art. 20)

O art. 20, incisos I, II e IV, da EC 103/2019  (o inciso III trata apenas dos servidores públicos) assegura a aposentadoria dos filiados ao RGPS até 13/11/2019 que cumpram os seguintes requisitos:

- 57 anos de idade se mulher e 60 anos de idade, se homem;

- 30 anos de contribuição se mulher e 35 anos de contribuição, se homem;

- "pedágio" (período de contribuição adicional) correspondente ao tempo que, na data de entrada em vigor da EC 103/2019, faltaria para atingir o tempo mínimo de contribuição de 30 anos (mulher) ou 35 anos (homem).

Em resumo:

| *Idade Mínima* |  | *Tempo de contribuição* |  | "Pedágio" |
| :------------- | :------------- | :------------- | :------------- | :------------- |
| *Mulher* | *Homem* | *Mulher* | *Homem* | 100% do tempo de contribuição que, em 13/11/2019, faltava para completar 30 anos de contribuição (mulher) ou 35 anos de contribuição (homem) |
| 57 | 60 | 30 | 35 | 100% do tempo de contribuição que, em 13/11/2019, faltava para completar 30 anos de contribuição (mulher) ou 35 anos de contribuição (homem) |

Nesta regra, há uma redução, em 05 anos na idade e no tempo de contribuição mínima para os professores da educação infantil, ensino fundamental e médio (§ 1º).

O valor da RMI da aposentadoria concedida com base no art. 20 da EC 103/2019 corresponderá a 100% do salário de benefício até que lei disciplina o cálculo dos benefícios do RGPS (EC 103/2019, art. 20, § 2º, II, c/c o art. 26, § 3º, I).
